services:
  # (Optional) Watchtower service for automatic updates of containers.
  # Useful for keeping your environment up-to-date without manual intervention.
  watchtower:
    image: containrrr/watchtower:1.7.1
    container_name: watchtower
    command:
      - "--label-enable" # Enable updates for containers with specific labels.
      - "--interval"
      - "30" # Interval in seconds for checking updates.
      - "--rolling-restart" # Restart containers one at a time to avoid downtime.
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  server:
    image: ghcr.io/hostupdev/website:${HOSTUP_WEBSITE_TAG:-latest}
    networks:
      # (Optional) Enable if using Traefik for reverse proxy.
      - public
    # (Optional) Enable replication for horizontal scaling and high availability.
    deploy:
      mode: replicated
      replicas: 3
    # (Optional) Configure Traefik labels for reverse proxy integration.
    # Requires Traefik to be set up and connected to the `public` network.
    labels:
      - traefik.enable=true
      - traefik.docker.network=public
      - traefik.http.services.hostup-website.loadbalancer.server.port=8080
      - traefik.http.services.hostup-website.loadbalancer.server.scheme=http
      - traefik.http.routers.hostup-website-https.entrypoints=websecure
      - traefik.http.routers.hostup-website-https.rule=Host(`${HOSTUP_WEBSITE_DOMAIN:?HOSTUP_WEBSITE_DOMAIN not set}`)
      - traefik.http.routers.hostup-website-https.tls=true
      - traefik.http.routers.hostup-website-https.tls.certresolver=cloudflare
      # (Optional) Enable updates for this service via Watchtower.
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped

networks:
  # (Optional) Frontend network for reverse proxy (e.g., Traefik).
  public:
    external: true
